language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
node_js:
  - '12'
git:
  depth: 3
script:
  - yarn build
notifications:
  email:
    reciepients:
      - noel.platzi.spa.37@gmail.com
    on_success: always
    on_failure: always
# manda emails(notificaciones) cuando es exitoso  o fallo
deploy:
  provider: pages
  skip-cleanup: true
  keep:history: true
  github-token: $GITHUB_TOKEN
  local-dir: dist/
  target-branch: gh-pages
  commit_message: "Deploy del proyecto"
  on:
    branch: master
# En target-branch debe ser gh-pages sino no publica en github
# El GITHUBG_TOKEN, lo creas en Github y  lo registras como variable en travis.